name: Cypress Tests

on: [push]

env:
  CYPRESS_HOST: https://ufo.camera

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: cypress run
