name: Cypress Tests

on:
  schedule:
    - cron:  '0 1 * * *'
  push:
    branches:
      - "*"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_HOST: https://ufo.camera

      - name: Save Cypress screenshots and videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: e2e-cypress
          path: |
            ./cypress/screenshots/
            ./cypress/videos/
